[package]
name = "insertcsv_rust"
version = "0.1.0"
authors = ["keisuke <e40keisuke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
dotenv = "0.9.0"
