[package]
name = "mysqlinsert"
version = "0.1.0"
authors = ["keisuke <e40keisuke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.0"
mysql = "*"
dotenv = "0.9.0"
rpassword = "4.0"


